version: '3.5'
services:
    chama-app:
        image: togree.backend:latest
        build: .
        container_name: chama-app
        restart: unless-stopped
        env_file: .env
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - NODE_ENV=${NODE_ENV}
        ports:
            - '3000:3000'
        depends_on:
            - db
        command: sh -c "npm run migrate && npm run seed && npm run start"
        networks:
            - backend

    db:
        image: postgres:12.3-alpine
        healthcheck:
            test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'root']
            timeout: 45s
            interval: 10s
            retries: 10
        restart: always
        container_name: backend.db
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - PORT=${DB_PORT}
        ports:
            - '5432:${DB_PORT}'
        volumes:
            - ./src/db/initialize_db.sql:/docker-entrypoint-initdb.d/initialize_db.sql
            - /var/lib/postgresql/data
        networks:
            - backend

networks:
    backend:
        name: backend
